//
//  UserProfile.swift
//  HealthBar
//
//  Created by Claude on 3/31/26.
//

import Foundation
import SwiftData

/// Stores the onboarding health profile for a user.
///
/// One document per user. All queries must filter by userId == currentUserId
/// and fetchLimit = 1. If duplicates exist, keep the most recently updated.
///
/// Firestore path: users/{userId}/profile/userProfile
@Model
final class UserProfile {

    // MARK: - Identity

    var id: UUID = UUID()

    /// Firebase UID — required for per-user scoping and Firestore sync.
    /// Defaults to "legacy" so pre-migration records don't crash.
    var userId: String = "legacy"

    /// The user's display name, synced from Firestore account/info on login.
    /// Inline default = lightweight SwiftData migration; no schema version bump needed.
    var displayName: String = ""

    // MARK: - Avatar (D3a)

    /// Preset-avatar selection: an icon id + a color id from `AvatarCatalog`.
    /// Optional + inline nil default = lightweight SwiftData migration; nil (either
    /// field) ⇒ initials fallback at every render site. Owner-authored via the
    /// picker — like `displayName`, avatar is preserved across full-profile upserts
    /// (deliberately excluded from `upsertUserProfile`'s in-place field copy).
    var avatarIcon: String? = nil
    var avatarColor: String? = nil

    // MARK: - Demographics

    /// "male" or "female"
    var sex: String = "male"

    /// Clamped 13–80 at input time.
    var age: Int = 25

    /// Always stored in kg. Clamped 30–300 at input time.
    var weightKg: Double = 70.0

    /// Always stored in cm. Clamped 120–230 at input time.
    var heightCm: Double = 170.0

    /// Always stored in kg. Converted from imperial at input time.
    var goalWeightKg: Double = 65.0

    // MARK: - Goal Pacing

    /// 0.5, 1.0, 1.5, or 2.0 lbs per week.
    var weeklyPaceLbs: Double = 1.0

    // MARK: - Lifestyle

    /// "sedentary", "light", "moderate", "active", "very_active"
    var activityLevel: String = "moderate"

    /// "standard", "keto", "vegan", "vegetarian", "paleo", "mediterranean"
    var dietStyle: String = "standard"

    /// Clamped 2–5 at input time.
    var mealsPerDay: Int = 3

    /// Subset of ["gluten", "dairy", "nuts", "soy", "eggs"]. Empty if none.
    var allergies: [String] = []

    /// "poor", "fair", "good"
    var sleepQuality: String = "fair"

    /// "low", "moderate", "high"
    var stressLevel: String = "moderate"

    // MARK: - AI Output

    /// Two-sentence coaching tip generated by Claude. Fallback is set if API fails.
    var aiTip: String = ""

    // MARK: - Status

    /// Set to true after the user completes all 14 steps and results are saved.
    var setupCompleted: Bool = false

    // MARK: - Timestamps

    var createdAt: Date = Date()
    var updatedAt: Date = Date()

    // MARK: - Initializer

    init(
        id: UUID = UUID(),
        userId: String,
        sex: String,
        age: Int,
        weightKg: Double,
        heightCm: Double,
        goalWeightKg: Double,
        weeklyPaceLbs: Double,
        activityLevel: String,
        dietStyle: String,
        mealsPerDay: Int,
        allergies: [String],
        sleepQuality: String,
        stressLevel: String,
        aiTip: String = "",
        setupCompleted: Bool = false,
        createdAt: Date = Date(),
        updatedAt: Date = Date()
    ) {
        self.id = id
        self.userId = userId
        self.sex = sex
        self.age = age
        self.weightKg = weightKg
        self.heightCm = heightCm
        self.goalWeightKg = goalWeightKg
        self.weeklyPaceLbs = weeklyPaceLbs
        self.activityLevel = activityLevel
        self.dietStyle = dietStyle
        self.mealsPerDay = mealsPerDay
        self.allergies = allergies
        self.sleepQuality = sleepQuality
        self.stressLevel = stressLevel
        self.aiTip = aiTip
        self.setupCompleted = setupCompleted
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}
